<?php

use PHPUnit\Framework\TestCase;

class MainTest extends TestCase
{
	private $main;
	protected function setUp(): void
	{
		$this->main = new Main();
		//parent::setUp(); // TODO: Change the autogenerated stub
	}
	
	protected function tearDown(): void
	{
		//parent::tearDown(); // TODO: Change the autogenerated stub
	}
	
	
}